# Generated by Django 4.2.1 on 2023-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_name", models.CharField(blank=True, max_length=50, null=True)),
                ("cat_image", models.ImageField(upload_to="category/")),
            ],
        ),
    ]
