# Generated by Django 4.2.1 on 2023-05-24 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flipkart", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("product_image", models.ImageField(upload_to="product/")),
                (
                    "product_description",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("product_price", models.IntegerField(blank=True, null=True)),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flipkart.category",
                    ),
                ),
            ],
        ),
    ]
